# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 16:51
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name_plural': '文章列表'},
        ),
        migrations.AddField(
            model_name='content',
            name='picture_url',
            field=models.ImageField(default='upload/1pic_hd.jpg', max_length=200, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Category', verbose_name='上级节点'),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='content',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
