# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180717_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.BooleanField(default=False, verbose_name='展示位置'),
        ),
        migrations.AddField(
            model_name='banner',
            name='isshow',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
