# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180719_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture_url',
            field=models.ImageField(default='/media/upload/1pic_hd.jpg', max_length=200, upload_to='upload', verbose_name='标题图片'),
        ),
    ]
