# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180719_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='upload/1pic_hd.jpg', max_length=400, upload_to='img', verbose_name='图片')),
                ('isshow', models.BooleanField(default=False, verbose_name='是否展示')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='picture_url',
            field=models.ImageField(default='upload/1pic_hd.jpg', max_length=200, upload_to='upload', verbose_name='标题图片'),
        ),
    ]
